# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        image_adapter:
            local:
                directory: '%kernel.project_dir%/public/media'
                lazy: ~ # boolean (default "false")
                writeFlags: ~
                linkHandling: ~
                permissions: ~
    filesystems:
        my_filesystem:
            adapter: image_adapter
            cache: ~
            alias: ~
            mount: media_file_fs
            visibility: public
